### ISSUE TITLE
Error happens at Install Segmentator

### ISSUE THREAD

**Issue by xiaotiancai899** [VinAIResearch/ISBNet#10]
When I run the command
 'cmake .. \
-DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` \
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") \
-DCMAKE_INSTALL_PREFIX=`python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'` '

The error happens:
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/bin/nvcc
CMake Error in /mnt/d/student/Documents/software/wsl/isbnet/ISBNet-master/ISBNet-master/segmentator/csrc/build/CMakeFiles/CMake
Tmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_017f8".

CMake Error in /mnt/d/student/Documents/software/wsl/isbnet/ISBNet-master/ISBNet-master/segmentator/csrc/build/CMakeFiles/CMake
Tmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_017f8".
-- Configuring incomplete, errors occurred!

How do I solve this problem? Thanks in advance!

**Comment by ngoductuanlhp** [comment]
I think the problem is that CMake cannot find the path to the Cuda compiler. You could check the current cuda version on your computer by typing `nvcc --version` and then following this instruction [https://github.com/NVlabs/instant-ngp/issues/25](https://github.com/NVlabs/instant-ngp/issues/25).
