### ISSUE TITLE
Error: Expected more than 1 value per channel when training

### ISSUE THREAD

**Issue by xiaotiancai899** [VinAIResearch/ISBNet#12]
I cannot use batch_size more than 1 when training ISBNet using this command 'python3 tools/train.py configs/scannetv2/isbnet_scannetv2.yaml --trainall --exp_name default'. Then this error occurs. 
' raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 224])'

How to solve this error? Thanks in advance!!!!

**Comment by ngoductuanlhp** [comment]
This is because `BatchNorm` layer expects more than 1 batch size during training. You can try training with `batch_size>=2 `, or reducing `max_npoint` int the config file.

**Comment by xiaotiancai899** [comment]
> This is because `BatchNorm` layer expects more than 1 batch size during training. You can try training with `batch_size>=2 `, or reducing `max_npoint` in the config file.

I have to use batch_size=1, if not, the program will occur bugs. So I have to reduce the number of max_npoint, but which number should I set it? Reduce half of it once?

**Comment by ngoductuanlhp** [comment]
You could set `max_npoint` to 200k or 100k to avoid OOM during training. If you want to set `batch_size=1`, try freezing all BatchNorm layers during training:
```
for m in model.modules():
      if isinstance(m, nn.BatchNorm1d):
           m.eval()
```

**Comment by xiaotiancai899** [comment]
> You could set `max_npoint` to 200k or 100k to avoid OOM during training. If you want to set `batch_size=1`, try freezing all BatchNorm layers during training:
> 
> ```
> for m in model.modules():
>       if isinstance(m, nn.BatchNorm1d):
>            m.eval()
> ```

I wonder where these codes should be placed, which file. Thank you so much for your attention and participation.

**Comment by ngoductuanlhp** [comment]
You can put them below this line https://github.com/VinAIResearch/ISBNet/blob/7c18fdb9e68ab5f5b53c00713a659626f788d2fc/tools/train.py#L54
