### ISSUE TITLE
python - m http.server 6008 Serving HTTP on 0.0.0.0 port 6008 (http://0.0.0.0:6008/) ...

### ISSUE THREAD

**Issue by xiaotiancai899** [VinAIResearch/ISBNet#13]
I run this command 'python - m http.server 6008'. Then get output like this 
Serving HTTP on 0.0.0.0 port 6008 (http://0.0.0.0:6008/) ...
But when I open this link, The webpage cannot show at all. How can I solve this problem? Thanks in advance!!!

**Comment by ngoductuanlhp** [comment]
Maybe using a different port number can solve this issue.

**Comment by buggogogo** [comment]
Try waiting a few more minutes? I think it will take time to link the file to the url to load completely.

**Comment by YuQiao0303** [comment]
Hi. Save issue for me.  'http://0.0.0.0:6008  seems' not working:
嗯… 无法访问此页面网址为http://0.0.0.0:6008/ 的页面可能存在问题，或者已永久移动到新的网址。
ERR_ADDRESS_INVALID

http://localhost:6008/  # this one works for me.
