### ISSUE TITLE
Some problems on visualize stpls3d?

### ISSUE THREAD

**Issue by buggogogo** [VinAIResearch/ISBNet#14]
Hello Author！
Your research is excellent and I benefit a lot from it.
I trained my dataset,and the result is excellent! My dataset is a corn plant point cloud and is not as large as stpls3d. After model training, the plant is cut into parts. I want to know how to visualize multiple trained files at the same time so that I can see how the whole corn plant is segmented at the same time. I would also like to know if there is a way to save the displayed split file as a colored point cloud file with annotations for easy viewing?
I look forward to your response and thank you very much for your work.

**Comment by ngoductuanlhp** [comment]
You can load multiple files at the same time and add them to the visualizer, i.e.:
```
import pyviz3d.visualizer as viz
v = viz.Visualizer()

# xyz1, rgb1: 1st point cloud
# xyz2. rgb2: 2nd point cloud

v.add_points('pc1', xyz1, rgb1, point_size=15) 
v.add_points('pc2', xyz2, rgb2, point_size=15) 
```
Make sure that `xyz1` and `xyz2` are in the global coordinate. You can also concatenate` [xyz1, xyz2] ` and  `[rgb1, rgb2]` to create a single point cloud containing all these points and save it as a numpy file.

**Comment by buggogogo** [comment]
Thank you ! I will try it!
