### ISSUE TITLE
About scannetv2 hidden test upload

### ISSUE THREAD

**Issue by 3171228612** [VinAIResearch/ISBNet#15]
What else should be done to handle pred_masks after test output before submitting them to the authorities? After I output the masks, the assessment fails all the time

**Comment by ngoductuanlhp** [comment]
You should follow our instructions to export the predictions in the correct format of ScanNetV2 benchmark, i.e.:
`python3 tools/test.py configs/scannetv2/isbnet_benchmark_scannetv2.yaml <checkpoint_file> --out <output_dir>`

The function `save_single_instance` in `tools/test.py` will map the predicted `class_id` to the corresponding `benchmark_class_id`, then write to the .txt file. Ensure that the total number of files in the test set is 100 and follow the instruction at [https://kaldir.vc.in.tum.de/scannet_benchmark/documentation](https://kaldir.vc.in.tum.de/scannet_benchmark/documentation) to zip the folder correctly.

**Comment by 3171228612** [comment]
Thank you for your explanation
