### ISSUE TITLE
How to test with STPLS3D no.26-28 datasets without labels?

### ISSUE THREAD

**Issue by Sophiscaty-C** [VinAIResearch/ISBNet#17]
I try to test with STPLS3D no.26-28 datasets (by changing config prefix to 'test') but I got this error:
![image](https://github.com/VinAIResearch/ISBNet/assets/61674480/dfdd3549-ec8b-43c7-966e-c26317af8812)
Thanks!
Looking forward to replies.

**Comment by Sophiscaty-C** [comment]
Thanks!That worked.
And seems like the result labels are all added with an extra 1 which making the range come to 2-15, is that also a bug?
![image](https://github.com/VinAIResearch/ISBNet/assets/61674480/264f5c98-4dce-4c3b-a1d9-a23959f9ed41)

**Comment by ngoductuanlhp** [comment]
For the STPLS3D dataset, there are 14 foreground classes, then the predicted class_id ranges from 0->13. During evaluation, we add with an extra 1 to distinguish them from the background class (0). Thus the `cls` value ranges from 1->14.

**Comment by Sophiscaty-C** [comment]
Thanks for your replies!

**Comment by huanghuang113** [comment]
Hi@Sophiscaty-C, how did you test the stpls3d dataset, do you need to change ''prefix: 'val_250m' '' to, ''prefix: 'test' '', I put the test file in the test folder, using python3 tools/test.py configs/isbnet_ stpls3d.yaml work_dirs/stpls3d/exp/latest.pth Can I use the model for testing with this command?

**Comment by WS517** [comment]
@Sophiscaty-C,how did you test the stpls3d dataset,Can you elaborate on the procedure, thank you very much!
