### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by aoligei178** [VinAIResearch/ISBNet#2]
Hello! Thank you for your awesome work for 3D instance segmentation. I want to know that how many GPU did you use and how long does it take to train your network on S3DIS. Thank you!

**Comment by ngoductuanlhp** [comment]
Hi,
Thanks for your interest in our work!

On S3DIS dataset, we use a single V100 GPU to train the model. Pre-training the backbone from scratch takes around 16 hours (with `batch_size=16`), or you could fine-tune the backbone trained on ScanNetV2 with fewer epoches. Training the entire network takes around 28 hours (with `batch_size=12`). Setting `fp16=True` in the cfg files could also speed up the training time and reduce the memory consumtion.
