### ISSUE TITLE
question about the model test

### ISSUE THREAD

**Issue by jongmin4422** [VinAIResearch/ISBNet#22]
@ngoductuanlhp
Hello, thanks for the great works!

I have some question about the testing a model on stpls3d datasets.
I'm using gpu with 24gb memory.

A cuda out of memory error occurs when running test.py through the setting in config.py. (batch size: 1, num_workers:16, fp16: Ture)
Did you have any idea to slove this problem?
Is it impossible to run with 24gb gpu memory?

Thank you.

**Comment by ngoductuanlhp** [comment]
I answered your question at https://github.com/VinAIResearch/ISBNet/issues/24#issue-1765338336 .
Thank you.

**Comment by huanghuang113** [comment]
> @ngoductuanlhp Hello, thanks for the great works!
> 
> I have some question about the testing a model on stpls3d datasets. I'm using gpu with 24gb memory.
> 
> A cuda out of memory error occurs when running test.py through the setting in config.py. (batch size: 1, num_workers:16, fp16: Ture) Did you have any idea to slove this problem? Is it impossible to run with 24gb gpu memory?
> 
> Thank you.

Hi, I've trained my model about the stpls3d dataset now, but I'm not sure how to test it, can you tell me these details about where to put the dataset and the command to test it?

**Comment by WS517** [comment]
@minimini-1,I would like to know how you style the test against the stpls3d dataset, can you elaborate on the procedure, thank you very much!
