### ISSUE TITLE
AssertionError: No instance result - results/pred_instance/scene0011_00.txt.

### ISSUE THREAD

**Issue by xiaotiancai899** [VinAIResearch/ISBNet#26]
When I use visualization.py for the scannet200 dataset visualization. An error occurred. The command I used is: python tools/visualization.py --prediction_path results/ --out output/

Traceback (most recent call last):
File "tools/visualization.py", line 606, in
xyz, rgb, boxes = get_coords_color(opt)
File "tools/visualization.py", line 435, in get_coords_color
assert os.path.isfile(instance_file), "No instance result - {}.".format(instance_file)
AssertionError: No instance result - results/pred_instance/scene0011_00.txt.

Any ideas about this? Thanks so much in advance!!!

**Comment by ngoductuanlhp** [comment]
It means that the prediction file does not exist. Maybe your pre-trained model predicts no instance in that particular scene.
