### ISSUE TITLE
About stpls3d training

### ISSUE THREAD

**Issue by cainiaoshidai** [VinAIResearch/ISBNet#3]
Hi,
    I get an error when I train on the stpls3d dataset.

>  File "D:/Instance_Segmentation/ISBNet-master/tools/train.py", line 309, in <module>
>     main()
>   File "D:/Instance_Segmentation/ISBNet-master/tools/train.py", line 300, in main
>     train(epoch, model, optimizer, scheduler, scaler, train_loader, cfg, logger, writer)
>   File "D:/Instance_Segmentation/ISBNet-master/tools/train.py", line 70, in train
>     loss, log_vars = model(batch, return_loss=True, epoch=epoch - 1)
>   File "D:\Anaconda3\envs\tf_to\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\Instance_Segmentation\ISBNet-master\isbnet\model\isbnet.py", line 220, in forward
>     return self.forward_train(**batch, epoch=epoch)
>   File "D:\Instance_Segmentation\ISBNet-master\isbnet\util\utils.py", line 172, in wrapper
>     return func(*new_args, **new_kwargs)
>   File "D:\Instance_Segmentation\ISBNet-master\isbnet\model\isbnet.py", line 361, in forward_train
>     voxel_instance_labels, subsample_idxs, instance_cls, instance_box, dc_batch_offsets, batch_size
>   File "D:\Instance_Segmentation\ISBNet-master\isbnet\model\model_utils.py", line 657, in get_subsample_gt
>     instance_labels_b = subsample_instance_labels[start:end]
> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> 
> Process finished with exit code 1

I'm running on a single RTX 4090, even if the batch size is set to 1.
When I try to set `use_spp_pool=True`, this error will not be displayed, but it will bring a vast GPU memory usage.
Can you give me some advice?
Thanks.
Best

**Comment by ngoductuanlhp** [comment]
Hi,
Thanks for your interest in our work!

First, you could set CUDA_LAUNCH_BLOCKING=1 and re-run the script to check exactly which function causes this error.
Second, did you pre-train the backbone before training the entire network? I guess that you trained the entire network from scratch which sometimes causes ambiguous inputs to the Local Aggregator.
Third, we only test our model on Ubuntu. Thus we cannot ensure that it will work perfectly on Windows.

Best.
