### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Rolandxx7** [VinAIResearch/ISBNet#31]
Dear author @ngoductuanlhp ,

I use this command to train the model for the stpls3d dataset and load the pre-trained backbone in the config file: `python tools/train.py  --trainall --exp_name testtest1`

However. I meet this problem after running the above command:
`2023-08-11 14:39:56,588 - INFO - missing keys in source state_dict: point_aggregator1.mlp_module1.layer0.conv.weight, point_aggregator1.mlp_module1.layer0.bn.bn.weight, point_aggregator1.mlp_module1.layer0.bn.bn.bias, point_aggregator1.mlp_module1.layer0.bn.bn.running_mean, point_aggregator1.mlp_module1.layer0.bn.bn.running_var, point_aggregator1.mlp_module1.layer1.conv.weight, point_aggregator1.mlp_module1.layer1.bn.bn.weight, point_aggregator1.mlp_module1.layer1.bn.bn.bias, point_aggregator1.mlp_module1.layer1.bn.bn.running_mean, point_aggregator1.mlp_module1.layer1.bn.bn.running_var, point_aggregator1.mlp_module2.layer0.conv.weight, point_aggregator1.mlp_module2.layer0.bn.bn.weight, point_aggregator1.mlp_module2.layer0.bn.bn.bias, point_aggregator1.mlp_module2.layer0.bn.bn.running_mean, point_aggregator1.mlp_module2.layer0.bn.bn.running_var, point_aggregator1.mlp_module3.0.conv.weight, point_aggregator1.mlp_module3.0.bn.bn.weight, point_aggregator1.mlp_module3.0.bn.bn.bias, point_aggregator1.mlp_module3.0.bn.bn.running_mean, point_aggregator1.mlp_module3.0.bn.bn.running_var, point_aggregator1.mlp_module3.1.conv.weight, point_aggregator1.mlp_module3.1.bn.bn.weight, point_aggregator1.mlp_module3.1.bn.bn.bias, point_aggregator1.mlp_module3.1.bn.bn.running_mean, point_aggregator1.mlp_module3.1.bn.bn.running_var, point_aggregator2.mlp_module1.layer0.conv.weight, point_aggregator2.mlp_module1.layer0.bn.bn.weight, point_aggregator2.mlp_module1.layer0.bn.bn.bias, point_aggregator2.mlp_module1.layer0.bn.bn.running_mean, point_aggregator2.mlp_module1.layer0.bn.bn.running_var, point_aggregator2.mlp_module1.layer1.conv.weight, point_aggregator2.mlp_module1.layer1.bn.bn.weight, point_aggregator2.mlp_module1.layer1.bn.bn.bias, point_aggregator2.mlp_module1.layer1.bn.bn.running_mean, point_aggregator2.mlp_module1.layer1.bn.bn.running_var, point_aggregator2.mlp_module2.layer0.conv.weight, point_aggregator2.mlp_module2.layer0.bn.bn.weight, point_aggregator2.mlp_module2.layer0.bn.bn.bias, point_aggregator2.mlp_module2.layer0.bn.bn.running_mean, point_aggregator2.mlp_module2.layer0.bn.bn.running_var, point_aggregator2.mlp_module3.0.conv.weight, point_aggregator2.mlp_module3.0.bn.bn.weight, point_aggregator2.mlp_module3.0.bn.bn.bias, point_aggregator2.mlp_module3.0.bn.bn.running_mean, point_aggregator2.mlp_module3.0.bn.bn.running_var, point_aggregator2.mlp_module3.1.conv.weight, point_aggregator2.mlp_module3.1.bn.bn.weight, point_aggregator2.mlp_module3.1.bn.bn.bias, point_aggregator2.mlp_module3.1.bn.bn.running_mean, point_aggregator2.mlp_module3.1.bn.bn.running_var, inst_shared_mlp.layers.0.weight, inst_shared_mlp.layers.1.weight, inst_shared_mlp.layers.1.bias, inst_shared_mlp.layers.1.running_mean, inst_shared_mlp.layers.1.running_var, inst_shared_mlp.layers.3.weight, inst_shared_mlp.layers.3.bias, inst_shared_mlp.layers.4.weight, inst_shared_mlp.layers.4.bias, inst_shared_mlp.layers.4.running_mean, inst_shared_mlp.layers.4.running_var, inst_sem_head.layers.0.weight, inst_sem_head.layers.1.weight, inst_sem_head.layers.1.bias, inst_sem_head.layers.1.running_mean, inst_sem_head.layers.1.running_var, inst_sem_head.layers.3.weight, inst_sem_head.layers.4.weight, inst_sem_head.layers.4.bias, inst_sem_head.layers.4.running_mean, inst_sem_head.layers.4.running_var, inst_sem_head.layers.6.weight, inst_sem_head.layers.6.bias, inst_conf_head.layers.0.weight, inst_conf_head.layers.1.weight, inst_conf_head.layers.1.bias, inst_conf_head.layers.1.running_mean, inst_conf_head.layers.1.running_var, inst_conf_head.layers.3.weight, inst_conf_head.layers.4.weight, inst_conf_head.layers.4.bias, inst_conf_head.layers.4.running_mean, inst_conf_head.layers.4.running_var, inst_conf_head.layers.6.weight, inst_conf_head.layers.6.bias, inst_box_head.layers.0.weight, inst_box_head.layers.1.weight, inst_box_head.layers.1.bias, inst_box_head.layers.1.running_mean, inst_box_head.layers.1.running_var, inst_box_head.layers.3.weight, inst_box_head.layers.4.weight, inst_box_head.layers.4.bias, inst_box_head.layers.4.running_mean, inst_box_head.layers.4.running_var, inst_box_head.layers.6.weight, inst_box_head.layers.6.bias, mask_tower.0.0.weight, mask_tower.0.1.weight, mask_tower.0.1.bias, mask_tower.0.1.running_mean, mask_tower.0.1.running_var, mask_tower.1.0.weight, mask_tower.1.1.weight, mask_tower.1.1.bias, mask_tower.1.1.running_mean, mask_tower.1.1.running_var, mask_tower.2.0.weight, mask_tower.2.1.weight, mask_tower.2.1.bias, mask_tower.2.1.running_mean, mask_tower.2.1.running_var, mask_tower.3.weight, mask_tower.3.bias, inst_mask_head.0.0.weight, inst_mask_head.0.1.weight, inst_mask_head.0.1.bias, inst_mask_head.0.1.running_mean, inst_mask_head.0.1.running_var, inst_mask_head.1.0.weight, inst_mask_head.1.1.weight, inst_mask_head.1.1.bias, inst_mask_head.1.1.running_mean, inst_mask_head.1.1.running_var, inst_mask_head.2.weight, inst_mask_head.2.bias
2023-08-11 14:39:56,589 - INFO - Training
[1]    31433 segmentation fault (core dumped)  CUDA_VISIBLE_DEVICES=3 python tools/train.py  --trainall --exp_name testtest1`

Could u please help me to solve this problem, many thanks!

**Comment by ngoductuanlhp** [comment]
This problem may occur when you import the `torch_scatter` library. Try to re-install it (https://github.com/rusty1s/pytorch_scatter) with the correct cuda and torch version.
