### ISSUE TITLE
checkpoint for ScanNet val seems wrong (only 6M)

### ISSUE THREAD

**Issue by YuQiao0303** [VinAIResearch/ISBNet#34]
Hi authors,
Thank you for this amazing work! 

I try to download the checkpoint for ScanNet val, but found in Google Drive that it's only 6M (file name is head_3dyco_scannetv2_val.pth, from link [https://drive.google.com/file/d/19FYLM5SzcQSKYR4r9iChauf5cleoXC_H/view](https://drive.google.com/file/d/19FYLM5SzcQSKYR4r9iChauf5cleoXC_H/view)).
Still, I try to use it with:
```python3 tools/test.py configs/scannetv2/isbnet_scannetv2.yaml dataset/pretrained/head_3dyco_scannetv2_val.pth --out out/scannetv2```,
and as expected, it raises the following error:
>$ python3 tools/test.py configs/scannetv2/isbnet_scannetv2.yaml dataset/pretrained/head_3dyco_scannetv2_val.pth --out out/scannetv2
2023-08-23 14:38:33,330 - INFO - Load state dict from dataset/pretrained/head_3dyco_scannetv2_val.pth
Traceback (most recent call last):
  File "tools/test.py", line 197, in <module>
    main()
  File "tools/test.py", line 100, in main
    load_checkpoint(args.checkpoint, logger, model)
  File "/home/yuqiao/ISBNet/isbnet/util/utils.py", line 118, in load_checkpoint
    state_dict = torch.load(checkpoint, map_location=lambda storage, loc: storage.cuda(device))
  File "/root/miniconda3/envs/jimr_pro/lib/python3.8/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/envs/jimr_pro/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

It seems that the wrong .pth file has been uploaded to Google Drive? I wonder if it's possible for you to verify and fix it? Thank you!!

**Comment by ngoductuanlhp** [comment]
Checkpoint link is updated.
Best.

**Comment by YuQiao0303** [comment]
> Checkpoint link is updated. Best.

Thank you so much. I tried and it worked.
