### ISSUE TITLE
Checkpoint of pretrain_scannetv2_benchmark.pth

### ISSUE THREAD

**Issue by mengcaopku** [VinAIResearch/ISBNet#36]
Could you please share the pre-trained checkpoint of 'pretrains/trainval/pretrain_scannetv2_benchmark.pth' mentioned in the config file isbnet_benchmark_scannetv2.yaml. Thanks a lot!

**Comment by ngoductuanlhp** [comment]
Here [Google Drive](https://drive.google.com/file/d/1YPSnVD0hXY8gN7o2_yjsInWh1gd3BfOl/view?usp=sharing).
Best.
