### ISSUE TITLE
Why the results on the test dataset is nan under the isbnet_benchmark_scannetv2.yaml config?

### ISSUE THREAD

**Issue by mengcaopku** [VinAIResearch/ISBNet#37]
Thanks for sharing the pretrain_scannetv2_trainval.pth. However, I have encountered the Nan results when evaluating the test dataset. Could you please share some possible reasons?

<img width="816" alt="image" src="https://github.com/VinAIResearch/ISBNet/assets/96517392/c8dc782a-7e80-44bf-acb7-8eb120d42ff3">

**Comment by ngoductuanlhp** [comment]
The only way to evaluate the results on the test dataset is to export the results and submit them to the ScanNet server. Please follow the instructions [here](https://github.com/VinAIResearch/ISBNet/issues/15#issuecomment-1564008612)
