### ISSUE TITLE
How to visualize?

### ISSUE THREAD

**Issue by dufolk** [VinAIResearch/ISBNet#4]
I tried to train S3DIS dataset and visualize it. Tell me how to realize that, PLEASE!

**Comment by ngoductuanlhp** [comment]
Hi @dufolk 

We update the visualization guide [here](https://github.com/VinAIResearch/ISBNet/tree/master/visualization). The script to visualize the S3DIS dataset is [vis_s3dis](https://github.com/VinAIResearch/ISBNet/blob/master/visualization/vis_s3dis.py).

Best.
