### ISSUE TITLE
Validation checkpoint's result about S3DIS

### ISSUE THREAD

**Issue by RongkunYang** [VinAIResearch/ISBNet#41]
Hello, dear author. Thank you for your great work.
When I validated the result on the S3DIS dataset Area 5, I found that the given checkpoint obtain a not good result, all the AP is 0. 
Could you please offer the correct checkpoints, Thank you.

**Comment by ngoductuanlhp** [comment]
Hi @RongkunYang,
We just updated the config file of S3DIS with our new pre-trained weight. Could you pull the newest version and try again?
