### ISSUE TITLE
How to train the checkpoint of my datasets?

### ISSUE THREAD

**Issue by wowluna** [VinAIResearch/ISBNet#42]
Hi authors!
Thank you for releasing this amazing work!
Now, I have my own dataset similar to S3dis, but not the same scene. How can I train my own point cloud dataset and get a checkpoint?

Best wishes！
luna

**Comment by ngoductuanlhp** [comment]
Thank you for your interest in our work. To adapt our method to a new dataset, you need to create a new Dataset module, inherited from our `CustomDataset`, it will define how to read your own point cloud (including rgb and xyz) as well as the semantic and instance labels, and define the train-val split. If you do not have the superpoint for your data, you could create a "dummy" superpoint as we do in the Replica dataset [here](https://github.com/VinAIResearch/ISBNet/blob/master/isbnet/data/replica.py). Then you need to create a new config file, defining the number of semantic and instance classes, and the model's hyper-parameter.

**Comment by wowluna** [comment]
Thank you for your reply!

Best.

**Comment by jianuo1128** [comment]
@wowluna Hello! My self-made dataset is also organized in the S3DIS format. I have no idea how to obtain SuperPoints. May I ask if the virtual superpoint method mentioned above has solved your previous problem? Can it be trained and tested normally? Can normal and reasonable instance segmentation visualization results be obtained?
