### ISSUE TITLE
What does the parameter spp mean?

### ISSUE THREAD

**Issue by wowluna** [VinAIResearch/ISBNet#43]
Hi!
When I was reading the code, I encountered an incomprehensible parameter 'spp'. What does it mean?

Best!

**Comment by ngoductuanlhp** [comment]
Sorry for this inconvenience. 'spp' means superpoint. You can read more about the superpoint used in our method here: [SuperPoint Transformer](https://github.com/drprojects/superpoint_transformer).

Best.
