### ISSUE TITLE
Hidden Test Set 

### ISSUE THREAD

**Issue by trandangtrungduc** [VinAIResearch/ISBNet#46]
My question is "Is the scale of confidence score important when you check the results on benchmark website?"
If I have 2 pred_masks with confident scores of 0.9 and 0.6, will the evaluation results be different or similar from if I have those 2 pred_masks with confident scores of 0.4 and 0.1 on a different scale?

Thank you very much.

**Comment by ngoductuanlhp** [comment]
I have tested on the validation set of ScanNet: regardless of the scale used (0.0 to 1.0 or 0.0 to 2.0), when the relative confidence scores of the predictions remain the same, the results remain consistent.
