### ISSUE TITLE
How can I inference on a custom dataset without labels?

### ISSUE THREAD

**Issue by XuDewen** [VinAIResearch/ISBNet#48]
Hello author, I have some cloudpoint data but no annotation labels. My data only includes XYZ and RGB values, without semantic labels or instance labels. How can I inference on a custom dataset without labels?

Thank you !

**Comment by ngoductuanlhp** [comment]
You could modify the dataloader to load only XYZ and RGB values, then create dummy `spp` like [this](https://github.com/VinAIResearch/ISBNet/blob/44beb835a25b91d98a7b8ad35b90969b941b8f3b/isbnet/data/replica.py#L23) and dummy `semantic_label`, `instance_label` like [this](https://github.com/VinAIResearch/ISBNet/blob/44beb835a25b91d98a7b8ad35b90969b941b8f3b/isbnet/data/scannetv2.py#L37).

**Comment by samsondawit** [comment]
@XuDewen , hello, were you able to make an inference?
