### ISSUE TITLE
S3DIS Data Preparation Error

### ISSUE THREAD

**Issue by trandangtrungduc** [VinAIResearch/ISBNet#5]
I got this error as shown image when I tried to run the "prepare_data.sh" for S3DIS dataset. I think the problem came from the data file (auditorium_1.txt), but is there any solution to this problem?

![image](https://user-images.githubusercontent.com/69638253/235417640-85e01fb9-c2f1-4866-8172-ac41a24ec922.png)

Thank you.

**Comment by ngoductuanlhp** [comment]
The raw S3DIS dataset contains some minor errors. You could fix them by manually removing the invalid characters in .txt files. We also upload the preprocess version of S3DIS at [Google Drive](https://drive.google.com/file/d/1vSyytTRPinPAcrJCBvGtOt19cf7tnVrD/view?usp=share_link). You can download and use it directly.

Best.
