### ISSUE TITLE
How to convert s3dis .txt format to superpoints data

### ISSUE THREAD

**Issue by XuDewen** [VinAIResearch/ISBNet#50]
Can anyone tell me the detailed process of generating a superpoints file (Box2Mask: [superpoints](https://datasets.d2.mpi-inf.mpg.de/box2mask/segment_labels.tar.gz) )from the .txt files of the S3DIS dataset? 

Thank you!

**Comment by ngoductuanlhp** [comment]
You could check this paper [Superpoint Transformer](https://github.com/drprojects/superpoint_transformer).
