### ISSUE TITLE
Does the Segmentator require meshes as input? 

### ISSUE THREAD

**Issue by aycatakmaz** [VinAIResearch/ISBNet#58]
Dear authors,

Thank you for this great work!

I have a question regarding the superpoint computation which seems to employ the Segmentator implementation from [this repository](https://github.com/Karbo123/segmentator). If I understand correctly, the function to compute the segments require meshes as input as it relies on the normals and faces. While one can estimate the normals for a point cloud input as well, it seems tricky to obtain a similar estimation for the faces. 

Is this possible to run this method on pure point cloud data (for instance from a laser scan) when one does not have access to any mesh reconstruction?

Does this mean that one can run ISBNet only when the reconstructed mesh is available? Similarly, does this imply a similar condition for the follow-up work Open3DIS, which utilizes the super point computation from this repository?

Thank you very much in advance!

Best,
Ayca

**Comment by ngoductuanlhp** [comment]
Hi @aycatakmaz,

For datasets with 3D meshes such as ScanNet, we use the link you mentioned above to generate the superpoints. For datasets without 3D meshes, we utilize the algorithm provided in [SPT](https://github.com/drprojects/superpoint_transformer/tree/master) to calculate the superpoint.

Best.

**Comment by kaoutar-elmouh** [comment]
> Salut@aycatakmaz,
> 
> Pour les jeux de données avec des maillages 3D tels que ScanNet, nous utilisons le lien que vous avez mentionné ci-dessus pour générer les superpoints. Pour les ensembles de données sans maillages 3D, nous utilisons l'algorithme fourni dans [SPT](https://github.com/drprojects/superpoint_transformer/tree/master) pour calculer le superpoint.
> 
> Meilleur.
hello,
I have the same question about superpoint generation because I want to do the same with my custom data. Can you tell me which algorithm you use?

**Comment by aycatakmaz** [comment]
Hi @ngoductuanlhp 

Thank you very much for the quick response! This answers my question - I am closing the issue.
