### ISSUE TITLE
Error occurred while training stpls3d dataset

### ISSUE THREAD

**Issue by Wzy-lab** [VinAIResearch/ISBNet#59]
Thank you for your contribution to instance segmentation. I have a problem when training stpls3d data. I followed the documentation. Can you help me solve it?
<img width="1920" alt="Snipaste_2024-06-06_11-31-36" src="https://github.com/VinAIResearch/ISBNet/assets/55731073/3eb19050-29d8-49fc-8fc7-19db553d302b">

**Comment by huanghuang113** [comment]
Maybe you didn't set the (def get_instances) method correctly.
