### ISSUE TITLE
KeyError: 'placeholder"  in training epoch 259 (set total epoch 500 )

### ISSUE THREAD

**Issue by leJson** [VinAIResearch/ISBNet#7]
Hi authors:
     thank you for your wonderful work. I have run this repo successfully. But when I trained my own dataset , I met an error in training epoch 259 , called " KeyError: 'placeholder" , this error happen in 'tools/train.py' file , line 75 , in train. code 'meter_dicd(k).update(v)'
waiting for your help!
thanks

**Comment by leJson** [comment]
Hi authors:
     thank you for your wonderful work. I have run this repo successfully. But when I trained my own dataset , I met an error called " KeyError: 'placeholder" , this error happen in 'tools/train.py' file , line 75 , in train. code 'meter_dicd(k).update(v)'
      waiting for your help!
    thanks

**Comment by ngoductuanlhp** [comment]
We updated the `tools/train.py` file to fix this bug. You could check our new commit.

Thanks.
