### ISSUE TITLE
About stpls3d training error CUDA out of memory

### ISSUE THREAD

**Issue by kellieda** [VinAIResearch/ISBNet#9]
Hello!
Thanks for your excellent work on 3D instance segmentation. When I trained your network on STPLS, I used an NVIDIA A5000 25GB GPU. After training the first epoch, the validation error CUDA out of memory, even with the batch_size set to 1.
Can you give me some advice?
Waiting for your help
Thank you!

**Comment by TobyZhouWei** [comment]
Hi, I met the same problem before. I use the cloud GPU, so I can change the GPU easily. I used A40(48GB) * 1, the problems have been already solved.

**Comment by kellieda** [comment]
> Hi, I met the same problem before. I use the cloud GPU, so I can change the GPU easily. I used A40(48GB) * 1, the problems have been already solved.

Ok, thanks for your reply, I will try the cloud GPU.

**Comment by xiaotiancai899** [comment]
You can solve this problem by modifying the batch_size<=16. I used 1, then make it.

**Comment by LinLin1031** [comment]
I encountered the same problem. But if I don't use cloud GPU, how should I solve this problem?

**Comment by kellieda** [comment]
> I encountered the same problem. But if I don't use cloud GPU, how should I solve this problem?

Due to my poor hardware conditions, I only took the solution proposed by TobyZhouWei and used the cloud GPU to solve it.

**Comment by xiaotiancai899** [comment]
> I encountered the same problem. But if I don't use cloud GPU, how should I solve this problem?

You can solve this problem by decreasing the number of batch_size. As for me, I set the batch_size=1.
